import time
from pathlib import Path
from PIL import Image
from .base import Widget

class BadAppleWidget(Widget):
    """
    Renders the legendary 'Bad Apple!!' shadow art.
    Plays from a pre-built binary file 'bad_apple_32x32.bin'.
    Uses time-based frame selection to maintain correct playback speed.
    """
    FPS = 30.0 # Target playback speed
    
    def __init__(self, canvas_size):
        super().__init__(canvas_size)
        self.w, self.h = canvas_size
        self.start_time = None
        self.total_frames = 0
        self.raw_data = None
        self.frame_index = 0
        
        # Cache file generated by build script
        self.cache_file = Path("bad_apple_32x32.bin")
        if self.cache_file.exists():
            self._load_cache()

    def _load_cache(self):
        try:
            data = self.cache_file.read_bytes()
            if len(data) >= 128:
                self.total_frames = len(data) // 128
                self.raw_data = data
        except Exception:
            pass

    async def update(self):
        if self.raw_data is None:
            if self.cache_file.exists():
                self._load_cache()
            return

        if self.start_time is None:
            self.start_time = time.time()

        # Calculate which frame we SHOULD be on based on elapsed time
        elapsed = time.time() - self.start_time
        self.frame_index = int(elapsed * self.FPS) % self.total_frames

    def render(self) -> Image.Image:
        img = Image.new("RGB", (self.w, self.h), (0, 0, 0))
        
        if self.raw_data is None:
            # Just show a black screen or a small white pixel to indicate waiting for data
            img.putpixel((0, 0), (50, 50, 50))
            return img

        # Render current frame (128 bytes per 32x32 frame)
        start = self.frame_index * 128
        frame_bytes = self.raw_data[start:start+128]
        
        for i, byte in enumerate(frame_bytes):
            for bit in range(8):
                if (byte >> (7 - bit)) & 1:
                    pos = i * 8 + bit
                    x = pos % 32
                    y = pos // 32
                    if x < self.w and y < self.h:
                        img.putpixel((x, y), (255, 255, 255))
        
        return img
